### ISSUE TITLE
这是怎么回事

### ISSUE THREAD

**Issue by hzgz** [lala437/qaecms#1]
![image](https://user-images.githubusercontent.com/65755377/117150437-bc6acb00-adea-11eb-8d7a-7b8bbdaf9033.png)

**Comment by lala437** [comment]
请在你itv目录下 执行  composer install

**Comment by hzgz** [comment]
执行了，但是有错误。
![image](https://user-images.githubusercontent.com/65755377/117217990-eb0d9380-ae34-11eb-9a84-c80999af0a32.png)

**Comment by lala437** [comment]
看提示 执行 composer update
