### ISSUE TITLE
有个新的播放器了解一下

### ISSUE THREAD

**Issue by q105201520** [lala437/qaecms#2]
也是m3u8但是标识不是他的官网是pgplayer.com   老哥能不能加上

**Comment by lala437** [comment]
这个在后台直接添加播放器接口不就行了？

**Comment by q105201520** [comment]
不行哦，不是直连也不是官方和m3u8------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月3日(星期四) 晚上7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lala437/qaecms] 有个新的播放器了解一下 (#2)

**Comment by lala437** [comment]
那是个啥  我点进官网看到 就是个播放接口呀
